server.port: 8081

spring:
  application:
    name: reactive service
  datasource:
    url: jdbc:h2:mem:reactiveServiceDB;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialize: true
    driver-class-name: org.h2.Driver
    continue-on-error: false
    platform: h2
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  error:
    whitelabel.enabled: true